import { fileURLToPath } from "node:url";
import { defineConfig } from "vitest/config";

export default defineConfig({
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./apps/web", import.meta.url)),
      "@convex": fileURLToPath(new URL("./convex/_generated", import.meta.url)),
      "@anan/ag-ui": fileURLToPath(new URL("./packages/ag-ui/src/index.ts", import.meta.url)),
      "@anan/ag-ui/react": fileURLToPath(new URL("./packages/ag-ui/src/react/index.ts", import.meta.url)),
      "@anan/ag-ui/anan": fileURLToPath(new URL("./packages/ag-ui/src/anan/index.ts", import.meta.url)),
      "@anan/platform-core/auth-next": fileURLToPath(new URL("./packages/platform-core/src/auth-next.ts", import.meta.url)),
      "@anan/platform-core/classnames": fileURLToPath(new URL("./packages/platform-core/src/classnames.ts", import.meta.url)),
      "@anan/platform-core/convex-api": fileURLToPath(new URL("./packages/platform-core/src/convex-api.ts", import.meta.url)),
      "@anan/platform-core/errors": fileURLToPath(new URL("./packages/platform-core/src/errors.ts", import.meta.url)),
      "@anan/platform-core/locale": fileURLToPath(new URL("./packages/platform-core/src/locale.ts", import.meta.url)),
      "@anan/platform-core/session": fileURLToPath(new URL("./packages/platform-core/src/session.ts", import.meta.url)),
      "@anan/platform-core": fileURLToPath(new URL("./packages/platform-core/src/index.ts", import.meta.url)),
      "@anan/auth/client": fileURLToPath(new URL("./packages/auth/src/client/index.ts", import.meta.url)),
      "@anan/auth/react": fileURLToPath(new URL("./packages/auth/src/react/index.ts", import.meta.url)),
      "@anan/auth/resource-server": fileURLToPath(new URL("./packages/auth/src/resource-server/index.ts", import.meta.url)),
      "@anan/auth/scopes": fileURLToPath(new URL("./packages/auth/src/scopes/index.ts", import.meta.url)),
      "@anan/auth/server/oauth-provider": fileURLToPath(new URL("./packages/auth/src/server/oauth-provider.ts", import.meta.url)),
      "@anan/auth/server": fileURLToPath(new URL("./packages/auth/src/server/index.ts", import.meta.url)),
      "@anan/auth": fileURLToPath(new URL("./packages/auth/src/index.ts", import.meta.url)),
      "@anan/auth-sdk/authorization": fileURLToPath(new URL("./packages/auth-sdk/src/authorization/index.ts", import.meta.url)),
      "@anan/auth-sdk/client": fileURLToPath(new URL("./packages/auth-sdk/src/client/index.ts", import.meta.url)),
      "@anan/auth-sdk/errors": fileURLToPath(new URL("./packages/auth-sdk/src/errors/index.ts", import.meta.url)),
      "@anan/auth-sdk/oidc": fileURLToPath(new URL("./packages/auth-sdk/src/oidc/index.ts", import.meta.url)),
      "@anan/auth-sdk/react": fileURLToPath(new URL("./packages/auth-sdk/src/react/index.ts", import.meta.url)),
      "@anan/auth-sdk/server": fileURLToPath(new URL("./packages/auth-sdk/src/server/index.ts", import.meta.url)),
      "@anan/auth-sdk/testing": fileURLToPath(new URL("./packages/auth-sdk/src/testing/index.ts", import.meta.url)),
      "@anan/auth-sdk": fileURLToPath(new URL("./packages/auth-sdk/src/index.ts", import.meta.url)),
      "@anan/auth-client/web": fileURLToPath(new URL("./packages/auth-client/src/web.ts", import.meta.url)),
      "@anan/auth-client/admin": fileURLToPath(new URL("./packages/auth-client/src/admin.ts", import.meta.url)),
      "@anan/auth-client/forms": fileURLToPath(new URL("./packages/auth-client/src/forms.ts", import.meta.url)),
      "@anan/auth-client/external-apps": fileURLToPath(new URL("./packages/auth-client/src/externalApps.ts", import.meta.url)),
      "@anan/base-logic": fileURLToPath(new URL("./packages/base-logic/src/index.ts", import.meta.url)),
      "@anan/base-logic/http": fileURLToPath(new URL("./packages/base-logic/src/http.ts", import.meta.url)),
      "@anan/base-logic/language": fileURLToPath(new URL("./packages/base-logic/src/language.ts", import.meta.url)),
      "@anan/base-logic/providers": fileURLToPath(new URL("./packages/base-logic/src/providers.ts", import.meta.url)),
      "@anan/base-logic/retry": fileURLToPath(new URL("./packages/base-logic/src/retry.ts", import.meta.url)),
      "@anan/base-logic/safe-parse": fileURLToPath(new URL("./packages/base-logic/src/safe-parse.ts", import.meta.url)),
      "@anan/base-logic/text": fileURLToPath(new URL("./packages/base-logic/src/text.ts", import.meta.url)),
      "@anan/compliance-logic": fileURLToPath(new URL("./packages/compliance-logic/src/index.ts", import.meta.url)),
      "@anan/compliance-logic/org-type": fileURLToPath(new URL("./packages/compliance-logic/src/org-type.ts", import.meta.url)),
      "@anan/convex-adapters/api": fileURLToPath(new URL("./packages/convex-adapters/src/api.ts", import.meta.url)),
      "@anan/convex-adapters/repository": fileURLToPath(new URL("./packages/convex-adapters/src/repository.ts", import.meta.url)),
      "@anan/crm-logic": fileURLToPath(new URL("./packages/crm-logic/src/index.ts", import.meta.url)),
      "@anan/crm-logic/mappers": fileURLToPath(new URL("./packages/crm-logic/src/mappers.ts", import.meta.url)),
      "@anan/domain-contracts/anan-pro": fileURLToPath(new URL("./packages/domain-contracts/src/ananPro.ts", import.meta.url)),
      "@anan/domain-contracts/compliance": fileURLToPath(new URL("./packages/domain-contracts/src/compliance.ts", import.meta.url)),
      "@anan/domain-contracts/deals": fileURLToPath(new URL("./packages/domain-contracts/src/deals.ts", import.meta.url)),
      "@anan/domain-contracts/errors": fileURLToPath(new URL("./packages/domain-contracts/src/errors.ts", import.meta.url)),
      "@anan/domain-contracts/files": fileURLToPath(new URL("./packages/domain-contracts/src/files.ts", import.meta.url)),
      "@anan/domain-contracts/gcc-countries": fileURLToPath(new URL("./packages/domain-contracts/src/gccCountries.ts", import.meta.url)),
      "@anan/domain-contracts/inbox": fileURLToPath(new URL("./packages/domain-contracts/src/inbox.ts", import.meta.url)),
      "@anan/domain-contracts/market": fileURLToPath(new URL("./packages/domain-contracts/src/market.ts", import.meta.url)),
      "@anan/domain-contracts/notifications": fileURLToPath(new URL("./packages/domain-contracts/src/notifications.ts", import.meta.url)),
      "@anan/domain-contracts/oauth": fileURLToPath(new URL("./packages/domain-contracts/src/oauth.ts", import.meta.url)),
      "@anan/domain-contracts/offers": fileURLToPath(new URL("./packages/domain-contracts/src/offers.ts", import.meta.url)),
      "@anan/domain-contracts/org-api": fileURLToPath(new URL("./packages/domain-contracts/src/orgApi.ts", import.meta.url)),
      "@anan/domain-contracts/organization-api-keys": fileURLToPath(new URL("./packages/domain-contracts/src/organizationApiKeys.ts", import.meta.url)),
      "@anan/domain-contracts/organizations": fileURLToPath(new URL("./packages/domain-contracts/src/organizations.ts", import.meta.url)),
      "@anan/domain-contracts/profiles": fileURLToPath(new URL("./packages/domain-contracts/src/profiles.ts", import.meta.url)),
      "@anan/domain-contracts/projects": fileURLToPath(new URL("./packages/domain-contracts/src/projects.ts", import.meta.url)),
      "@anan/domain-contracts/properties": fileURLToPath(new URL("./packages/domain-contracts/src/properties.ts", import.meta.url)),
      "@anan/domain-contracts/session": fileURLToPath(new URL("./packages/domain-contracts/src/session.ts", import.meta.url)),
      "@anan/domain-contracts/verifications": fileURLToPath(new URL("./packages/domain-contracts/src/verifications.ts", import.meta.url)),
      "@anan/domain-contracts/workspace": fileURLToPath(new URL("./packages/domain-contracts/src/workspace.ts", import.meta.url)),
      "@anan/location-map/react": fileURLToPath(new URL("./packages/location-map/src/react/index.ts", import.meta.url)),
      "@anan/location-map/types": fileURLToPath(new URL("./packages/location-map/src/types.ts", import.meta.url)),
      "@anan/location-map": fileURLToPath(new URL("./packages/location-map/src/index.ts", import.meta.url)),
      "@anan/market-logic": fileURLToPath(new URL("./packages/market-logic/src/index.ts", import.meta.url)),
      "@anan/market-logic/normalizers": fileURLToPath(new URL("./packages/market-logic/src/normalizers.ts", import.meta.url)),
      "@anan/offers-logic": fileURLToPath(new URL("./packages/offers-logic/src/index.ts", import.meta.url)),
      "@anan/offers-logic/cases": fileURLToPath(new URL("./packages/offers-logic/src/cases.ts", import.meta.url)),
      "@anan/testing/oauth": fileURLToPath(new URL("./packages/testing/src/oauth.ts", import.meta.url)),
      "@anan/testing/profile": fileURLToPath(new URL("./packages/testing/src/profile.ts", import.meta.url)),
      "@anan/testing/react": fileURLToPath(new URL("./packages/testing/src/react.ts", import.meta.url)),
      "@anan/testing/repository": fileURLToPath(new URL("./packages/testing/src/repository.ts", import.meta.url)),
      "@anan/testing/route": fileURLToPath(new URL("./packages/testing/src/route.ts", import.meta.url)),
      "@anan/testing/session": fileURLToPath(new URL("./packages/testing/src/session.ts", import.meta.url)),
      "@anan/testing/vitest": fileURLToPath(new URL("./packages/testing/src/vitest.ts", import.meta.url)),
      "@anan/ui/admin": fileURLToPath(new URL("./packages/ui/src/admin/index.ts", import.meta.url)),
      "@anan/ui/auth": fileURLToPath(new URL("./packages/ui/src/auth/index.ts", import.meta.url)),
      "@anan/ui/chat": fileURLToPath(new URL("./packages/ui/src/chat/index.ts", import.meta.url)),
      "@anan/ui/docs": fileURLToPath(new URL("./packages/ui/src/docs/index.ts", import.meta.url)),
      "@anan/ui/forms": fileURLToPath(new URL("./packages/ui/src/forms/index.ts", import.meta.url)),
      "@anan/ui/oauth": fileURLToPath(new URL("./packages/ui/src/oauth/index.ts", import.meta.url)),
      "@anan/ui/public": fileURLToPath(new URL("./packages/ui/src/public/index.ts", import.meta.url)),
      "@anan/ui/workspace": fileURLToPath(new URL("./packages/ui/src/workspace/index.ts", import.meta.url)),
      "@anan/ui/button": fileURLToPath(new URL("./packages/ui/src/components/ui/button.tsx", import.meta.url)),
      "@anan/ui/dropdown-menu": fileURLToPath(new URL("./packages/ui/src/components/ui/dropdown-menu.tsx", import.meta.url)),
      "@anan/web-foundation/api": fileURLToPath(new URL("./packages/web-foundation/src/api.ts", import.meta.url)),
      "@anan/web-foundation/auth-session": fileURLToPath(new URL("./packages/web-foundation/src/auth-session.ts", import.meta.url)),
      "@anan/web-foundation/convex-provider": fileURLToPath(new URL("./packages/web-foundation/src/convex-provider.tsx", import.meta.url)),
      "@anan/web-foundation/fonts": fileURLToPath(new URL("./packages/web-foundation/src/fonts.ts", import.meta.url)),
      "@anan/web-foundation/locale": fileURLToPath(new URL("./packages/web-foundation/src/locale.ts", import.meta.url)),
      "@anan/web-foundation/media": fileURLToPath(new URL("./packages/web-foundation/src/media.ts", import.meta.url)),
      "@anan/web-foundation/theme": fileURLToPath(new URL("./packages/web-foundation/src/theme.tsx", import.meta.url)),
      "@anan/workspace-logic": fileURLToPath(new URL("./packages/workspace-logic/src/index.ts", import.meta.url)),
      "@anan/workspace-logic/zones": fileURLToPath(new URL("./packages/workspace-logic/src/zones.ts", import.meta.url)),
      react: fileURLToPath(new URL("./apps/web/node_modules/react", import.meta.url)),
      "react-dom": fileURLToPath(new URL("./apps/web/node_modules/react-dom", import.meta.url)),
      "lucide-react": fileURLToPath(new URL("./apps/web/node_modules/lucide-react", import.meta.url)),
      // Next runtime guard module: throws when imported from client.
      // In unit tests we stub it to a no-op.
      "server-only": fileURLToPath(new URL("./test/stubs/server-only.ts", import.meta.url)),
    },
  },
  test: {
    include: [
      "convex/**/*.test.{ts,tsx}",
      "frontend/src/**/*.test.{ts,tsx}",
      "apps/web/**/*.test.{ts,tsx}",
      "packages/**/*.test.{ts,tsx}",
      "web/**/*.test.{ts,tsx}",
    ],
    environment: "node",
    globals: false,
    testTimeout: 30_000,
    hookTimeout: 10_000,
  },
});
