import { formatLoc } from "./analyzeLib.mjs";

function table(md, headers, rows) {
  md.push(`| ${headers.join(" | ")} |`);
  md.push(`| ${headers.map(() => "---").join(" | ")} |`);
  for (const r of rows) md.push(`| ${r.join(" | ")} |`);
  md.push("");
}

function pushSummary(md, args) {
  const { scannedSourceFiles, oversizedFiles, longFunctions, deepNesting, risky } = args;
  md.push(`# Audit Tables (Generated)\n`);
  md.push(`Generated by \`scripts/audit/analyze.mjs\`.\n`);
  md.push(`- Scanned tracked source files: **${scannedSourceFiles}**`);
  md.push(`- Oversized files (>300 lines): **${oversizedFiles.length}**`);
  md.push(`- Long functions (>40 lines): **${longFunctions.length}**`);
  md.push(`- Deep nesting (>=3): **${deepNesting.length}**`);
  md.push(`- Convex \`.collect()\` occurrences: **${risky.convexCollectCalls.length}**`);
  md.push(`- Convex \`.filter((q)=>...)\` occurrences: **${risky.convexFilterQCalls.length}**`);
  md.push(`- \`useQuery(..., {})\` occurrences: **${risky.useQueryEmptyArgs.length}**`);
  md.push(`- \`ctx.db.get(...)\` inside loops: **${risky.ctxDbGetInLoop.length}**\n`);
}

function addOversized(md, oversizedFiles) {
  md.push(`## Oversized Files (>300 lines)\n`);
  table(md, ["File", "Lines"], oversizedFiles.map((x) => [`\`${x.file}\``, String(x.lines)]));
}

function addLongFunctions(md, longFunctions) {
  md.push(`## Long Functions (>40 lines)\n`);
  table(
    md,
    ["Location", "Function", "Owner", "Lines"],
    longFunctions.map((x) => [
      `\`${x.file}:${x.startLine}-${x.endLine}\``,
      `\`${x.name}\``,
      x.owner ? `\`${x.owner}\`` : "",
      String(x.lines),
    ])
  );
}

function addDeepNesting(md, deepNesting) {
  md.push(`## Deep Nesting (>=3)\n`);
  table(
    md,
    ["Location", "Function", "Owner", "Max Depth"],
    deepNesting.map((x) => [
      `\`${x.file}:${x.startLine}-${x.endLine}\``,
      `\`${x.name}\``,
      x.owner ? `\`${x.owner}\`` : "",
      String(x.maxNesting),
    ])
  );
}

function addTodo(md, todoFixme) {
  md.push(`## TODO/FIXME/XXX (Tracked Source)\n`);
  table(
    md,
    ["Location", "Text"],
    todoFixme.map((x) => [`\`${formatLoc(x.file, x.line)}\``, x.text.replace(/\|/g, "\\|")])
  );
}

function addRiskyPatterns(md, risky) {
  md.push(`## Risky Patterns Index\n`);
  md.push(`### Convex: \`.collect()\`\n`);
  table(
    md,
    ["Location", "Line"],
    risky.convexCollectCalls.map((x) => [`\`${formatLoc(x.file, x.line)}\``, x.text.replace(/\|/g, "\\|")])
  );

  md.push(`### Convex: \`.filter((q) => ...)\`\n`);
  table(
    md,
    ["Location", "Line"],
    risky.convexFilterQCalls.map((x) => [`\`${formatLoc(x.file, x.line)}\``, x.text.replace(/\|/g, "\\|")])
  );

  md.push(`### Frontend: \`useQuery(..., {})\`\n`);
  table(
    md,
    ["Location", "Line"],
    risky.useQueryEmptyArgs.map((x) => [`\`${formatLoc(x.file, x.line)}\``, x.text.replace(/\|/g, "\\|")])
  );

  md.push(`### Convex: \`ctx.db.get(...)\` Inside Loops\n`);
  table(
    md,
    ["Location", "Function", "Line"],
    risky.ctxDbGetInLoop.map((x) => [
      `\`${formatLoc(x.file, x.callLine)}\``,
      `\`${x.function}\``,
      x.text.replace(/\|/g, "\\|"),
    ])
  );
}

export function buildAuditTablesMarkdown(args) {
  const { scannedSourceFiles, analysis } = args;
  const md = [];
  pushSummary(md, {
    deepNesting: analysis.deepNesting,
    longFunctions: analysis.longFunctions,
    oversizedFiles: analysis.oversizedFiles,
    risky: analysis.risky,
    scannedSourceFiles,
  });
  addOversized(md, analysis.oversizedFiles);
  addLongFunctions(md, analysis.longFunctions);
  addDeepNesting(md, analysis.deepNesting);
  addTodo(md, analysis.todoFixme);
  addRiskyPatterns(md, analysis.risky);
  return md.join("\n");
}
