import type { ClientProperty } from "../types";

export const MOCK_PROPERTIES: ClientProperty[] = [
  {
    id: "demo-riyadh-olive",
    title: "Olive Residence Apartment",
    address: "Al Yasmin, Riyadh",
    location: "Riyadh",
    area: "Al Yasmin",
    price: 1180000,
    beds: 3,
    baths: 3,
    sqft: 1780,
    status: "ready",
    media: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80"],
    owner: {
      id: "broker-ahmed",
      type: "broker",
      name: "Ahmed Mansour",
      slug: "ahmed-mansour",
      isVerified: true,
    },
    aiSummary: "Balanced family apartment close to schools, daily retail, and two main roads.",
  },
  {
    id: "demo-riyadh-courtyard",
    title: "Courtyard Family Apartment",
    address: "Al Malqa, Riyadh",
    location: "Riyadh",
    area: "Al Malqa",
    price: 1320000,
    beds: 3,
    baths: 4,
    sqft: 1910,
    status: "new",
    media: ["https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80"],
    owner: {
      id: "developer-roshn",
      type: "RED",
      name: "Roshn",
      slug: "roshn",
      isVerified: true,
    },
    aiSummary: "Higher-spec finish, larger reception, and a stronger long-term appreciation profile.",
  },
  {
    id: "demo-riyadh-invest",
    title: "Investor Duplex Suite",
    address: "Hittin, Riyadh",
    location: "Riyadh",
    area: "Hittin",
    price: 960000,
    beds: 2,
    baths: 3,
    sqft: 1490,
    status: "ready",
    media: ["https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80"],
    owner: {
      id: "broker-sara",
      type: "broker",
      name: "Sara Alqahtani",
      slug: "sara-alqahtani",
      isVerified: true,
    },
    aiSummary: "Compact investment-oriented duplex with strong rental demand and flexible exit potential.",
  },
];
